actions:
  - type: "SubscriptionListView"
    condition: "SelectItem"
    action: "SpawnResourceGroupListView"
    takeFocus: true
  - type: "ResourceGroupListView"
    condition: "SelectItem"
    action: "SpawnResourceTypeListView"
    takeFocus: true
  # - type: "ResourceTypeListView"
  #   condition: "SelectItem"
  #   action: "SpawnVirtualMachineListView"
  #   takeFocus: true
  - type: "ResourceTypeListView"
    condition: "SelectItem"
    action: "SpawnAKSClusterListView"
    takeFocus: true
  - type: "VirtualMachineListView"
    condition: "SelectItem"
    action: "SpawnVirtualMachineDetailView"
    takeFocus: false
  - type: "VirtualMachineListView"
    condition: "RunCommand"
    action: "SpawnVirtualMachineCommandListView"
    takeFocus: true
  - type: "VirtualMachineListView"
    condition: "Interact"
    action: "SpawnVirtualMachineSerialConsoleView"
    takeFocus: true
  - type: "AKSClusterListView"
    condition: "SelectItem"
    action: "SpawnAKSClusterDetailView"
    takeFocus: true
  - type: "AKSClusterListView"
    condition: "Interact"
    action: "SpawnAKSClusterConsoleView"
    takeFocus: true
  - type: "Global"
    condition: "Quit"
    action: "Quit"
    takeFocus: true
key_mappings:
  - action: "SpawnResourceGroupListView"
    key: "Enter"
  - action: "SpawnResourceTypeListView"
    key: "Enter"
  - action: "SpawnVirtualMachineListView"
    key: "Enter"
  - action: "SpawnVirtualMachineDetailView"
    key: "Enter"
  - action: "SpawnVirtualMachineCommandListView"
    key: "Ctrl-R"
  - action: "SpawnVirtualMachineSerialConsoleView"
    key: "F5"
  - action: "SpawnAKSClusterListView"
    key: "Enter"
  - action: "SpawnAKSClusterDetailView"
    key: "Enter"
  - action: "SpawnAKSClusterConsoleView"
    key: "F5"
  - action: "Quit"
    key: "F12"
