actions:
  - type: "SubscriptionListView"
    condition: "SelectItem"
    action: "SpawnResourceGroupListView"
    takeFocus: true
  - type: "ResourceGroupListView"
    condition: "SelectItem"
    action: "SpawnResourceTypeListView"
    takeFocus: true
  - type: "ResourceTypeListView"
    condition: "SelectItem"
    action: "SpawnResourceListView"
    takeFocus: true
  - type: "ResourceListView"
    condition: "SelectItem"
    action: "SpawnResourceDetailView"
    takeFocus: true
  - type: "Global"
    condition: "Quit"
    action: "Quit"
    takeFocus: true
key_mappings:
  - action: "SpawnResourceGroupListView"
    key: "Enter"
  - action: "SpawnResourceTypeListView"
    key: "Enter"
  - action: "SpawnResourceListView"
    key: "Enter"
  - action: "SpawnResourceDetailView"
    key: "Enter"
  - action: "Quit"
    key: "F12"
