FROM mcr.microsoft.com/azurelinux/base/core:3.0
RUN mkdir -p /workdir
COPY . /workdir/.

RUN tdnf install -y \
	rpm-build \
	bash \
	make \
	python \
	golang \
	ca-certificates

WORKDIR /workdir
RUN make rpm
